import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function MethodologySection() {
	return (
		<Card>
			<CardHeader>
				<CardTitle>Methodology &amp; Disclaimers</CardTitle>
			</CardHeader>
			<CardContent className="space-y-5 text-sm leading-relaxed text-muted-foreground">
				{/* Trade selection pipeline */}
				<section>
					<h3 className="mb-1 font-semibold text-foreground">
						Trade Selection Pipeline
					</h3>
					<p>
						Every trading day follows a fixed automated pipeline. At 9:25 AM
						ET, the system scrapes social-media sentiment from multiple
						sources, identifies the most-discussed tickers, and feeds them
						into a GPT-5.4 analysis layer. The model scores each ticker on
						sentiment strength, catalyst quality, and risk profile, then
						selects the top-ranked option contracts for the day. All
						positions are opened at the market open and closed at 4:05 PM
						ET&mdash;no trades are held overnight.
					</p>
				</section>

				{/* Performance metrics */}
				<section>
					<h3 className="mb-1 font-semibold text-foreground">
						Performance Metrics
					</h3>
					<ul className="list-inside list-disc space-y-1">
						<li>
							<strong>Profit Factor</strong> &mdash; ratio of gross winning
							P&amp;L to gross losing P&amp;L. A value above 1.0 means the
							system is net profitable.
						</li>
						<li>
							<strong>Expectancy</strong> &mdash; average dollar P&amp;L
							per trade, accounting for both win rate and average win/loss
							size. Positive expectancy implies long-run profitability.
						</li>
						<li>
							<strong>Sharpe Ratio</strong> &mdash; risk-adjusted return
							calculated as the mean daily P&amp;L divided by its standard
							deviation. Higher values indicate more consistent returns.
						</li>
						<li>
							<strong>Max Drawdown</strong> &mdash; largest peak-to-trough
							decline in cumulative P&amp;L. Reflects the worst observed
							losing streak.
						</li>
						<li>
							<strong>Return on Capital (ROC)</strong> &mdash; net P&amp;L
							divided by total capital deployed. Measures how efficiently
							invested capital generates returns.
						</li>
					</ul>
				</section>

				{/* Options pricing context */}
				<section>
					<h3 className="mb-1 font-semibold text-foreground">
						Options Pricing Context
					</h3>
					<p>
						Entry prices are estimated at 9:30 AM using the contract&rsquo;s
						mark price (midpoint of bid/ask). Closing prices are recorded at
						4:05 PM ET using the same mark-price methodology. All P&amp;L
						figures assume single-contract positions (100 shares notional)
						and do not include commissions or slippage.
					</p>
				</section>

				{/* Data sources */}
				<section>
					<h3 className="mb-1 font-semibold text-foreground">
						Data Sources
					</h3>
					<p>
						Stock and option prices are sourced from the Schwab Market Data
						API. Sentiment data is aggregated from public social-media
						posts, financial news feeds, and community forums. All data is
						processed server-side and cached for historical lookup.
					</p>
				</section>

				{/* Disclaimers */}
				<section>
					<h3 className="mb-1 font-semibold text-foreground">Disclaimers</h3>
					<p>
						This dashboard is for informational and educational purposes
						only. Past performance does not guarantee future results. The
						trades shown are generated by an automated system and do not
						constitute financial advice. Options trading involves
						substantial risk and is not suitable for all investors. Always
						do your own research before making investment decisions.
					</p>
				</section>
			</CardContent>
		</Card>
	);
}
